const mongoose = require('mongoose');
require('dotenv').config();

const Level = require('./models/Level');
const Question = require('./models/Question');

const levels = [
  {
    levelNumber: 1,
    title: "Money Basics - भारतीय संदर्भ",
    description: "Learn the fundamentals of money in Indian context",
    introduction: "Welcome to your financial journey! In this level, you'll learn about Indian currency, banking, and digital payments. Understanding these basics is your first step toward financial mastery!",
    unlockCost: 0,
    rewardCoins: 100,
    icon: "💵",
    difficulty: "Beginner"
  },
  {
    levelNumber: 2,
    title: "Budgeting & Digital Payments",
    description: "Master budgeting and UPI payments",
    introduction: "A budget is your financial roadmap! Learn how to track income, manage expenses using Indian apps, and master UPI payments. This is the foundation of financial success!",
    unlockCost: 200,
    rewardCoins: 150,
    icon: "📊",
    difficulty: "Beginner"
  },
  {
    levelNumber: 3,
    title: "Saving & Government Schemes",
    description: "Discover Indian savings schemes and strategies",
    introduction: "Learn about PPF, NSC, Sukanya Samriddhi, and other Indian government schemes. Build your savings with schemes designed for Indian youth!",
    unlockCost: 400,
    rewardCoins: 200,
    icon: "🏦",
    difficulty: "Beginner"
  },
  {
    levelNumber: 4,
    title: "Credit & Indian Banking",
    description: "Learn about credit cards, loans, and CIBIL score",
    introduction: "Understand credit scores, Indian bank loans, credit cards, and how to build a strong CIBIL score that opens doors to opportunities.",
    unlockCost: 600,
    rewardCoins: 250,
    icon: "💳",
    difficulty: "Intermediate"
  },
  {
    levelNumber: 5,
    title: "Indian Stock Market",
    description: "Enter the world of NSE, BSE, and stock investing",
    introduction: "Learn about NIFTY, SENSEX, Demat accounts, and how to invest in Indian stocks through Zerodha, Groww, and other platforms!",
    unlockCost: 800,
    rewardCoins: 300,
    icon: "📈",
    difficulty: "Intermediate"
  },
  {
    levelNumber: 6,
    title: "Insurance in India",
    description: "Protect yourself with LIC and health insurance",
    introduction: "Learn about Indian insurance options including LIC policies, health insurance, term insurance, and IRDAI regulations.",
    unlockCost: 1000,
    rewardCoins: 350,
    icon: "🛡️",
    difficulty: "Intermediate"
  },
  {
    levelNumber: 7,
    title: "Indian Taxation",
    description: "Understand Income Tax, GST, PAN, and Aadhaar",
    introduction: "Master Indian tax system including Income Tax slabs, GST, PAN card requirements, and how to file ITR online!",
    unlockCost: 1200,
    rewardCoins: 400,
    icon: "🧾",
    difficulty: "Intermediate"
  },
  {
    levelNumber: 8,
    title: "Mutual Funds & SIP",
    description: "Learn about Indian mutual funds and systematic investing",
    introduction: "Discover how to invest through SIP, understand NAV, SEBI regulations, and choose the right mutual funds for your goals!",
    unlockCost: 1500,
    rewardCoins: 450,
    icon: "💰",
    difficulty: "Advanced"
  },
  {
    levelNumber: 9,
    title: "Indian Real Estate",
    description: "Understand property investment and housing loans",
    introduction: "Learn about home loans, EMI calculations, RERA regulations, and real estate investment in India!",
    unlockCost: 1800,
    rewardCoins: 500,
    icon: "🏠",
    difficulty: "Advanced"
  },
  {
    levelNumber: 10,
    title: "Advanced Wealth Building",
    description: "Master EPF, NPS, and retirement planning for Indians",
    introduction: "Learn about EPF, NPS, APY, and advanced strategies for building wealth as a young Indian professional!",
    unlockCost: 2000,
    rewardCoins: 1000,
    icon: "👑",
    difficulty: "Advanced"
  }
];

const questions = [
  // Level 1: Money Basics - Indian Context
  {
    levelNumber: 1,
    question: "What is the symbol for Indian Rupee?",
    options: ["$", "₹", "£", "€"],
    correctAnswer: 1,
    explanation: "₹ is the official symbol for Indian Rupee, designed by D. Udaya Kumar. It was adopted in 2010 and combines the Devanagari letter 'र' and Latin 'R'.",
    difficulty: "easy",
    topic: "Indian Currency",
    category: "Money Management",
    indiaSpecific: true,
    relatedTerms: ["Rupee", "INR", "Indian Currency"],
    ageRelevance: "all",
    practicalExample: "When you see ₹500 on a product, it means 500 Indian Rupees.",
    estimatedTime: 20
  },
  {
    levelNumber: 1,
    question: "What does RBI stand for?",
    options: ["Reserve Bank of India", "Rupee Banking Institute", "Regional Bank of India", "Real Banking Index"],
    correctAnswer: 0,
    explanation: "RBI stands for Reserve Bank of India. It is India's central bank that controls monetary policy, regulates banks, and manages currency.",
    difficulty: "easy",
    topic: "Indian Banking System",
    category: "Banking",
    indiaSpecific: true,
    relatedTerms: ["RBI", "Central Bank", "Monetary Policy"],
    ageRelevance: "all",
    practicalExample: "RBI decides the interest rates that affect your bank savings and loan EMIs.",
    estimatedTime: 25
  },
  {
    levelNumber: 1,
    question: "What is UPI?",
    options: ["Universal Payment Interface", "Unified Payment Interface", "Updated Payment Information", "Ultra Payment Integration"],
    correctAnswer: 1,
    explanation: "UPI stands for Unified Payments Interface. It's an instant real-time payment system that allows you to transfer money instantly using apps like Google Pay, PhonePe, Paytm.",
    difficulty: "easy",
    topic: "Digital Payments",
    category: "Digital Payments",
    indiaSpecific: true,
    relatedTerms: ["UPI", "Digital Payment", "GooglePay", "PhonePe", "BHIM"],
    ageRelevance: "all",
    practicalExample: "You can send ₹500 to a friend instantly using their UPI ID like name@paytm",
    estimatedTime: 30
  },
  {
    levelNumber: 1,
    question: "What is a PAN card used for in India?",
    options: ["Identity proof for pan purchases", "Permanent Account Number for tax purposes", "Pan India card for travel", "Payment Authentication Number"],
    correctAnswer: 1,
    explanation: "PAN (Permanent Account Number) is a 10-digit unique identification number issued by Income Tax Department. It's mandatory for filing taxes, opening bank accounts, and high-value transactions.",
    difficulty: "easy",
    topic: "Financial Documentation",
    category: "Financial Regulations",
    indiaSpecific: true,
    relatedTerms: ["PAN Card", "Income Tax", "Tax ID"],
    ageRelevance: "18-24",
    practicalExample: "You need PAN card to open a bank account or invest in mutual funds in India.",
    estimatedTime: 30
  },
  {
    levelNumber: 1,
    question: "What is the current repo rate approximately decided by RBI? (Answer may vary)",
    options: ["Around 2-3%", "Around 6-7%", "Around 15-20%", "Around 25-30%"],
    correctAnswer: 1,
    explanation: "The repo rate is the rate at which RBI lends money to commercial banks. It typically ranges around 6-7% and affects interest rates on loans and deposits.",
    difficulty: "medium",
    topic: "Interest Rates",
    category: "Banking",
    indiaSpecific: true,
    relatedTerms: ["Repo Rate", "RBI", "Interest Rate"],
    ageRelevance: "18-24",
    practicalExample: "When RBI increases repo rate, bank loan EMIs become more expensive.",
    estimatedTime: 35
  },
  {
    levelNumber: 1,
    question: "What is the full form of NEFT?",
    options: ["National Electronic Funds Transfer", "New Electronic Financial Transaction", "Net Electronic Fund Transfer", "National Easy Fund Transfer"],
    correctAnswer: 0,
    explanation: "NEFT stands for National Electronic Funds Transfer. It's a nationwide payment system that allows you to transfer funds from one bank to another in India.",
    difficulty: "easy",
    topic: "Bank Transfers",
    category: "Banking",
    indiaSpecific: true,
    relatedTerms: ["NEFT", "RTGS", "IMPS", "Bank Transfer"],
    ageRelevance: "all",
    practicalExample: "You can use NEFT to transfer ₹10,000 from your SBI account to a friend's HDFC account.",
    estimatedTime: 30
  },
  {
    levelNumber: 1,
    question: "Which of these is a nationalized bank in India?",
    options: ["HDFC Bank", "State Bank of India", "ICICI Bank", "Axis Bank"],
    correctAnswer: 1,
    explanation: "State Bank of India (SBI) is a nationalized (government-owned) bank. HDFC, ICICI, and Axis are private sector banks.",
    difficulty: "easy",
    topic: "Indian Banks",
    category: "Banking",
    indiaSpecific: true,
    relatedTerms: ["SBI", "Nationalized Bank", "Public Sector Bank"],
    ageRelevance: "all",
    practicalExample: "SBI is India's largest bank with branches in almost every city and town.",
    estimatedTime: 25
  },
  {
    levelNumber: 1,
    question: "What is Aadhaar?",
    options: ["A payment app", "A 12-digit unique identity number", "A credit card", "A loan scheme"],
    correctAnswer: 1,
    explanation: "Aadhaar is a 12-digit unique identity number issued by UIDAI to all Indian residents. It's used for identification, direct benefit transfer, and KYC verification.",
    difficulty: "easy",
    topic: "Identity Documents",
    category: "Financial Regulations",
    indiaSpecific: true,
    relatedTerms: ["Aadhaar", "UIDAI", "KYC"],
    ageRelevance: "all",
    practicalExample: "You need Aadhaar to open a bank account, get SIM card, or receive government subsidies.",
    estimatedTime: 30
  },
  {
    levelNumber: 1,
    question: "What does KYC stand for?",
    options: ["Keep Your Cash", "Know Your Customer", "Key Your Code", "Keep Yearly Credit"],
    correctAnswer: 1,
    explanation: "KYC stands for Know Your Customer. It's a verification process where banks collect your identity proof, address proof, and photos to prevent fraud and money laundering.",
    difficulty: "easy",
    topic: "Banking Compliance",
    category: "Banking",
    indiaSpecific: true,
    relatedTerms: ["KYC", "eKYC", "Verification"],
    ageRelevance: "13-17",
    practicalExample: "You need to complete KYC with PAN and Aadhaar to open a bank account.",
    estimatedTime: 30
  },
  {
    levelNumber: 1,
    question: "What is compound interest?",
    options: ["Simple interest paid twice", "Interest earned on both principal and previous interest", "Interest that is complex", "Interest only on original amount"],
    correctAnswer: 1,
    explanation: "Compound interest is interest calculated on the initial principal AND accumulated interest. In India, PPF, bank FDs, and most savings accounts use compound interest!",
    difficulty: "medium",
    topic: "Interest Concepts",
    category: "Money Management",
    indiaSpecific: false,
    relatedTerms: ["Compound Interest", "Simple Interest", "Interest Calculation"],
    ageRelevance: "all",
    practicalExample: "If you invest ₹10,000 at 8% annual compound interest, you'll have ₹10,800 after year 1 and ₹11,664 after year 2.",
    estimatedTime: 40
  },

  // Level 2: Budgeting & Digital Payments
  {
    levelNumber: 2,
    question: "Which app is NOT a UPI payment app in India?",
    options: ["Google Pay", "PhonePe", "Paytm", "WhatsApp"],
    correctAnswer: 3,
    explanation: "While WhatsApp has payment features in some countries, it's primarily a messaging app. Google Pay, PhonePe, and Paytm are dedicated UPI payment apps in India. (Note: WhatsApp Pay exists but is not as widely used)",
    difficulty: "easy",
    topic: "UPI Apps",
    category: "Digital Payments",
    indiaSpecific: true,
    relatedTerms: ["UPI Apps", "Google Pay", "PhonePe", "Paytm"],
    ageRelevance: "13-17",
    practicalExample: "You can scan QR codes at shops to pay using Google Pay or PhonePe.",
    estimatedTime: 25
  },
  {
    levelNumber: 2,
    question: "What is the 50/30/20 budget rule?",
    options: ["50% needs, 30% wants, 20% savings", "50% savings, 30% needs, 20% wants", "50% fun, 30% food, 20% rent", "Random numbers"],
    correctAnswer: 0,
    explanation: "The 50/30/20 rule allocates 50% to needs (rent, groceries), 30% to wants (entertainment, dining out), and 20% to savings/investments. Perfect for young Indians starting their career!",
    difficulty: "easy",
    topic: "Budgeting Rules",
    category: "Budgeting",
    indiaSpecific: false,
    relatedTerms: ["Budgeting", "50/30/20 Rule", "Money Management"],
    ageRelevance: "18-24",
    practicalExample: "If you earn ₹30,000/month, allocate ₹15,000 for needs, ₹9,000 for wants, and ₹6,000 for savings.",
    estimatedTime: 35
  },
  {
    levelNumber: 2,
    question: "What is the maximum daily UPI transaction limit for most banks?",
    options: ["₹10,000", "₹1,00,000", "₹5,00,000", "No limit"],
    correctAnswer: 1,
    explanation: "Most banks in India have a UPI transaction limit of ₹1,00,000 per day. This limit can vary by bank and can be customized in your banking app.",
    difficulty: "medium",
    topic: "UPI Limits",
    category: "Digital Payments",
    indiaSpecific: true,
    relatedTerms: ["UPI Limit", "Transaction Limit", "Daily Limit"],
    ageRelevance: "18-24",
    practicalExample: "You cannot transfer more than ₹1 lakh per day using UPI, so plan large payments accordingly.",
    estimatedTime: 30
  },
  {
    levelNumber: 2,
    question: "Which app can you use to track expenses in India?",
    options: ["All of these", "Walnut", "ET Money", "Money View"],
    correctAnswer: 0,
    explanation: "All these apps - Walnut, ET Money, and Money View - are popular Indian apps for expense tracking, budgeting, and financial management.",
    difficulty: "easy",
    topic: "Expense Tracking",
    category: "Budgeting",
    indiaSpecific: true,
    relatedTerms: ["Expense Tracking", "Budgeting Apps", "Financial Apps"],
    ageRelevance: "18-24",
    practicalExample: "Apps like Walnut automatically track expenses by reading SMS from your bank.",
    estimatedTime: 30
  },
  {
    levelNumber: 2,
    question: "What is BHIM app?",
    options: ["A gaming app", "Government's UPI payment app", "A social media app", "An investment app"],
    correctAnswer: 1,
    explanation: "BHIM (Bharat Interface for Money) is the Indian government's official UPI app developed by NPCI (National Payments Corporation of India).",
    difficulty: "easy",
    topic: "Government Apps",
    category: "Digital Payments",
    indiaSpecific: true,
    relatedTerms: ["BHIM", "UPI", "NPCI", "Government App"],
    ageRelevance: "all",
    practicalExample: "BHIM is a secure, government-backed app for making UPI payments.",
    estimatedTime: 25
  },
  {
    levelNumber: 2,
    question: "What is a fixed expense in Indian household context?",
    options: ["Movie tickets", "Rent/EMI", "Dining out", "Shopping"],
    correctAnswer: 1,
    explanation: "Fixed expenses are regular payments of the same amount each month. In India, this includes rent, home loan EMI, car loan EMI, insurance premiums, etc.",
    difficulty: "easy",
    topic: "Fixed Expenses",
    category: "Budgeting",
    indiaSpecific: true,
    relatedTerms: ["Fixed Expense", "EMI", "Rent"],
    ageRelevance: "18-24",
    practicalExample: "Your monthly rent of ₹12,000 or bike EMI of ₹3,500 are fixed expenses.",
    estimatedTime: 25
  },
  {
    levelNumber: 2,
    question: "What does EMI stand for?",
    options: ["Easy Money Interest", "Equated Monthly Installment", "Electronic Money Interface", "Extra Monthly Income"],
    correctAnswer: 1,
    explanation: "EMI stands for Equated Monthly Installment. It's a fixed payment you make every month to repay a loan (home, car, personal loan) in India.",
    difficulty: "easy",
    topic: "Loan Terminology",
    category: "Credit & Loans",
    indiaSpecific: false,
    relatedTerms: ["EMI", "Loan", "Monthly Payment"],
    ageRelevance: "18-24",
    practicalExample: "If you buy a phone worth ₹30,000 on EMI, you might pay ₹2,500 per month for 12 months.",
    estimatedTime: 30
  },
  {
    levelNumber: 2,
    question: "Which Indian fintech is known for 'Buy Now Pay Later'?",
    options: ["Zerodha", "Paytm Postpaid", "NSE", "RBI"],
    correctAnswer: 1,
    explanation: "Paytm Postpaid, along with apps like Simpl, LazyPay offer 'Buy Now Pay Later' (BNPL) services in India, allowing purchases with payment next month.",
    difficulty: "medium",
    topic: "BNPL Services",
    category: "Digital Payments",
    indiaSpecific: true,
    relatedTerms: ["Buy Now Pay Later", "BNPL", "Paytm Postpaid", "LazyPay"],
    ageRelevance: "18-24",
    practicalExample: "You can order food worth ₹500 using Paytm Postpaid and pay next month without interest.",
    estimatedTime: 30
  },
  {
    levelNumber: 2,
    question: "What is zero-based budgeting?",
    options: ["Having zero money", "Giving every rupee a job until income minus expenses equals zero", "Spending nothing", "Starting from scratch"],
    correctAnswer: 1,
    explanation: "Zero-based budgeting means allocating every single rupee of your income to specific categories (expenses, savings, investments) until you reach zero. Income - Expenses - Savings = 0",
    difficulty: "medium",
    topic: "Budgeting Methods",
    category: "Budgeting",
    indiaSpecific: false,
    relatedTerms: ["Zero-based Budgeting", "Budget Planning"],
    ageRelevance: "18-24",
    practicalExample: "If you earn ₹40,000, allocate every rupee: ₹20,000 needs + ₹12,000 wants + ₹8,000 savings = ₹40,000",
    estimatedTime: 40
  },
  {
    levelNumber: 2,
    question: "What is the maximum UPI transaction limit per transaction?",
    options: ["₹1,000", "₹10,000", "₹1,00,000", "₹10,00,000"],
    correctAnswer: 2,
    explanation: "The per-transaction limit for UPI is ₹1,00,000 for most payment types. However, for specific categories like IPO, it can be higher.",
    difficulty: "medium",
    topic: "UPI Limits",
    category: "Digital Payments",
    indiaSpecific: true,
    relatedTerms: ["UPI", "Transaction Limit"],
    ageRelevance: "18-24",
    practicalExample: "You can send maximum ₹1 lakh in a single UPI transaction.",
    estimatedTime: 30
  },

  // Level 3: Saving & Government Schemes
  {
    levelNumber: 3,
    question: "What does PPF stand for?",
    options: ["Public Provident Fund", "Personal Profit Fund", "Private Pension Fund", "Public Pension Fund"],
    correctAnswer: 0,
    explanation: "PPF stands for Public Provident Fund. It's a government-backed long-term savings scheme (15 years) with tax benefits under Section 80C and currently offering around 7-7.5% interest.",
    difficulty: "easy",
    topic: "Government Schemes",
    category: "Government Schemes",
    indiaSpecific: true,
    relatedTerms: ["PPF", "Public Provident Fund", "Tax Saving", "Section 80C"],
    ageRelevance: "18-24",
    practicalExample: "You can invest ₹500 to ₹1.5 lakh per year in PPF and get tax deduction.",
    estimatedTime: 35
  },
  {
    levelNumber: 3,
    question: "What is the minimum investment amount in PPF per year?",
    options: ["₹100", "₹500", "₹1,000", "₹5,000"],
    correctAnswer: 1,
    explanation: "The minimum investment in PPF is ₹500 per year and maximum is ₹1.5 lakh per year. You can deposit this amount in lump sum or installments.",
    difficulty: "medium",
    topic: "PPF Details",
    category: "Government Schemes",
    indiaSpecific: true,
    relatedTerms: ["PPF", "Investment Limit", "Minimum Investment"],
    ageRelevance: "18-24",
    practicalExample: "You can start PPF with just ₹500 per year, making it accessible for students and young professionals.",
    estimatedTime: 30
  },
  {
    levelNumber: 3,
    question: "What is Sukanya Samriddhi Yojana?",
    options: ["Scheme for boys", "Savings scheme for the girl child", "Education loan", "Health insurance"],
    correctAnswer: 1,
    explanation: "Sukanya Samriddhi Yojana is a government savings scheme for girl children. Parents can open account before girl turns 10, invest and earn tax-free returns for her education/marriage.",
    difficulty: "easy",
    topic: "Girl Child Schemes",
    category: "Government Schemes",
    indiaSpecific: true,
    relatedTerms: ["Sukanya Samriddhi", "Girl Child Scheme", "SSY"],
    ageRelevance: "all",
    practicalExample: "Parents can invest ₹250-₹1.5 lakh per year for their daughter's future.",
    estimatedTime: 35
  },
  {
    levelNumber: 3,
    question: "What does NSC stand for?",
    options: ["National Savings Certificate", "New Saving Card", "National Security Credit", "Net Savings Cash"],
    correctAnswer: 0,
    explanation: "NSC stands for National Savings Certificate. It's a government-backed fixed-income investment with 5-year maturity and tax benefits under Section 80C.",
    difficulty: "easy",
    topic: "Government Certificates",
    category: "Government Schemes",
    indiaSpecific: true,
    relatedTerms: ["NSC", "National Savings Certificate", "Tax Saving"],
    ageRelevance: "18-24",
    practicalExample: "You can buy NSC from any post office with minimum ₹1,000 investment.",
    estimatedTime: 30
  },
  {
    levelNumber: 3,
    question: "What is the lock-in period for PPF?",
    options: ["5 years", "10 years", "15 years", "20 years"],
    correctAnswer: 2,
    explanation: "PPF has a lock-in period of 15 years, but partial withdrawals are allowed after 7 years. You can extend in blocks of 5 years after maturity.",
    difficulty: "medium",
    topic: "PPF Details",
    category: "Government Schemes",
    indiaSpecific: true,
    relatedTerms: ["PPF", "Lock-in Period", "Maturity"],
    ageRelevance: "18-24",
    practicalExample: "If you open PPF at age 20, it will mature when you're 35.",
    estimatedTime: 30
  },
  {
    levelNumber: 3,
    question: "What is PMJDY?",
    options: ["Prime Minister Job Development Yojana", "Pradhan Mantri Jan Dhan Yojana", "Public Money Jan Dhan Yojana", "Prime Money Janta Development Yojana"],
    correctAnswer: 1,
    explanation: "PMJDY (Pradhan Mantri Jan Dhan Yojana) is a financial inclusion program that provides zero-balance bank accounts with RuPay debit card and accident insurance.",
    difficulty: "medium",
    topic: "Financial Inclusion",
    category: "Government Schemes",
    indiaSpecific: true,
    relatedTerms: ["PMJDY", "Jan Dhan", "Zero Balance Account"],
    ageRelevance: "all",
    practicalExample: "Anyone can open a Jan Dhan account with zero balance and get a free RuPay card.",
    estimatedTime: 35
  },
  {
    levelNumber: 3,
    question: "What is the interest rate on Post Office Savings Account approximately?",
    options: ["2-3%", "4-5%", "10-12%", "15-20%"],
    correctAnswer: 1,
    explanation: "Post Office Savings Account offers around 4% interest per annum, which is competitive with regular bank savings accounts and backed by Government of India.",
    difficulty: "medium",
    topic: "Post Office Schemes",
    category: "Savings",
    indiaSpecific: true,
    relatedTerms: ["Post Office", "Savings Account", "Interest Rate"],
    ageRelevance: "all",
    practicalExample: "You can open a Post Office savings account with minimum ₹500 and get 4% interest.",
    estimatedTime: 30
  },
  {
    levelNumber: 3,
    question: "What is 'paying yourself first'?",
    options: ["Buying things for yourself", "Saving/investing before spending", "Paying yourself a salary", "Getting a paycheck"],
    correctAnswer: 1,
    explanation: "Paying yourself first means automatically saving or investing money (like in PPF, SIP) as soon as you receive income, before spending on anything else.",
    difficulty: "easy",
    topic: "Saving Strategy",
    category: "Savings",
    indiaSpecific: false,
    relatedTerms: ["Saving Strategy", "Investment Priority"],
    ageRelevance: "18-24",
    practicalExample: "When you get your ₹30,000 salary, immediately transfer ₹5,000 to PPF before spending.",
    estimatedTime: 30
  },
  {
    levelNumber: 3,
    question: "Which scheme is best for senior citizens in India?",
    options: ["Sukanya Samriddhi", "Senior Citizens Savings Scheme (SCSS)", "PPF", "Student loan"],
    correctAnswer: 1,
    explanation: "Senior Citizens Savings Scheme (SCSS) is specifically designed for people above 60, offering around 8% interest with tax benefits.",
    difficulty: "medium",
    topic: "Senior Citizen Schemes",
    category: "Government Schemes",
    indiaSpecific: true,
    relatedTerms: ["SCSS", "Senior Citizens", "Retirement"],
    ageRelevance: "25-30",
    practicalExample: "Your grandparents can invest in SCSS and get regular quarterly interest payments.",
    estimatedTime: 30
  },
  {
    levelNumber: 3,
    question: "What is an emergency fund?",
    options: ["Money for fun emergencies", "Savings for unexpected expenses like medical bills", "Credit card for emergencies", "Money borrowed from family"],
    correctAnswer: 1,
    explanation: "An emergency fund is savings kept aside specifically for unexpected expenses like medical emergencies, job loss, or urgent repairs. Ideally 3-6 months of expenses.",
    difficulty: "easy",
    topic: "Emergency Planning",
    category: "Savings",
    indiaSpecific: false,
    relatedTerms: ["Emergency Fund", "Rainy Day Fund"],
    ageRelevance: "all",
    practicalExample: "If your monthly expenses are ₹20,000, aim for ₹60,000-₹1,20,000 emergency fund.",
    estimatedTime: 35
  },

  // Level 4: Credit & Indian Banking
  {
    levelNumber: 4,
    question: "What is CIBIL score?",
    options: ["Criminal record", "Credit score ranging from 300-900", "Bank balance", "Income proof"],
    correctAnswer: 1,
    explanation: "CIBIL score is your credit score ranging from 300-900. A higher score (750+) indicates good credit behavior and helps you get loans and credit cards easily with better interest rates.",
    difficulty: "easy",
    topic: "Credit Score",
    category: "Credit & Loans",
    indiaSpecific: true,
    relatedTerms: ["CIBIL", "Credit Score", "Credit Report"],
    ageRelevance: "18-24",
    practicalExample: "A CIBIL score of 800 helps you get home loan at 8% instead of 9% interest.",
    estimatedTime: 35
  },
  {
    levelNumber: 4,
    question: "What is a good CIBIL score in India?",
    options: ["300-500", "500-650", "900-1000", "750-900"],
    correctAnswer: 3,
    explanation: "A CIBIL score between 750-900 is considered excellent in India. Scores above 750 significantly improve your chances of loan approval with better terms.",
    difficulty: "medium",
    topic: "Credit Score Range",
    category: "Credit & Loans",
    indiaSpecific: true,
    relatedTerms: ["CIBIL Score", "Credit Rating", "Good Credit"],
    ageRelevance: "18-24",
    practicalExample: "Banks prefer customers with 750+ CIBIL score for home loans and credit cards.",
    estimatedTime: 30
  },
  {
    levelNumber: 4,
    question: "What is the full form of CIBIL?",
    options: ["Credit Information Bureau India Limited", "Central Indian Bank Interest Limit", "Credit Index Banking in India Limited", "Central Information Bureau of India Limited"],
    correctAnswer: 0,
    explanation: "CIBIL stands for Credit Information Bureau (India) Limited. It's India's first credit information company, now called TransUnion CIBIL.",
    difficulty: "easy",
    topic: "Credit Bureau",
    category: "Credit & Loans",
    indiaSpecific: true,
    relatedTerms: ["CIBIL", "Credit Bureau", "TransUnion CIBIL"],
    ageRelevance: "18-24",
    practicalExample: "CIBIL maintains credit records of 600+ million Indians.",
    estimatedTime: 30
  },
  {
    levelNumber: 4,
    question: "What affects your CIBIL score negatively?",
    options: ["Paying EMI on time", "Maintaining low credit utilization", "Missing credit card payments", "Having a good income"],
    correctAnswer: 2,
    explanation: "Missing credit card payments or loan EMIs is one of the worst things for your CIBIL score. Also harmful: high credit utilization, multiple loan applications, and loan defaults.",
    difficulty: "easy",
    topic: "Credit Score Factors",
    category: "Credit & Loans",
    indiaSpecific: true,
    relatedTerms: ["CIBIL Score", "Credit Impact", "Payment Default"],
    ageRelevance: "18-24",
    practicalExample: "If you miss 2-3 credit card payments, your CIBIL score can drop by 50-100 points.",
    estimatedTime: 35
  },
  {
    levelNumber: 4,
    question: "What is credit utilization ratio?",
    options: ["How much credit you use vs. your credit limit", "Number of credit cards you have", "Your credit score", "Your income to loan ratio"],
    correctAnswer: 0,
    explanation: "Credit utilization ratio is the percentage of your credit limit that you're using. Keeping it below 30% is ideal for maintaining good CIBIL score.",
    difficulty: "medium",
    topic: "Credit Utilization",
    category: "Credit & Loans",
    indiaSpecific: false,
    relatedTerms: ["Credit Utilization", "Credit Limit", "CIBIL Score"],
    ageRelevance: "18-24",
    practicalExample: "If your credit card limit is ₹1,00,000, try to keep spending below ₹30,000 per month.",
    estimatedTime: 40
  },
  {
    levelNumber: 4,
    question: "What is APR on credit cards?",
    options: ["Annual Percentage Rate (interest charged)", "Average Payment Return", "Automatic Payment Reminder", "Annual Point Reward"],
    correctAnswer: 0,
    explanation: "APR (Annual Percentage Rate) is the yearly interest rate charged on outstanding credit card balance. In India, it typically ranges from 24-48% per annum.",
    difficulty: "medium",
    topic: "Credit Card Interest",
    category: "Credit & Loans",
    indiaSpecific: false,
    relatedTerms: ["APR", "Interest Rate", "Credit Card"],
    ageRelevance: "18-24",
    practicalExample: "If you don't pay credit card bill in full, you'll pay around 3-4% monthly interest (36-48% annually).",
    estimatedTime: 35
  },
  {
    levelNumber: 4,
    question: "What is the minimum age to apply for a credit card in India?",
    options: ["16 years", "18 years", "21 years", "25 years"],
    correctAnswer: 1,
    explanation: "You must be at least 18 years old to apply for a credit card in India. However, some banks may require you to be 21 and have a stable income.",
    difficulty: "easy",
    topic: "Credit Card Eligibility",
    category: "Credit & Loans",
    indiaSpecific: true,
    relatedTerms: ["Credit Card", "Age Requirement", "Eligibility"],
    ageRelevance: "13-17",
    practicalExample: "College students above 18 can get student credit cards with lower credit limits.",
    estimatedTime: 25
  },
  {
    levelNumber: 4,
    question: "What is 'credit card grace period'?",
    options: ["Extra time after due date without penalty", "Time between purchase and statement", "Interest-free period if you pay full bill", "Credit score improvement period"],
    correctAnswer: 2,
    explanation: "Credit card grace period is the interest-free period (typically 20-50 days) if you pay your entire bill before due date. No interest charged during this period.",
    difficulty: "medium",
    topic: "Credit Card Terms",
    category: "Credit & Loans",
    indiaSpecific: false,
    relatedTerms: ["Grace Period", "Credit Card", "Interest-free Period"],
    ageRelevance: "18-24",
    practicalExample: "Buy on Jan 1, statement on Jan 31, due date Feb 15 - pay full amount by Feb 15 = no interest!",
    estimatedTime: 40
  },
  {
    levelNumber: 4,
    question: "What is a secured credit card?",
    options: ["Card with high security features", "Card backed by fixed deposit", "Card for secure transactions", "Card with password"],
    correctAnswer: 1,
    explanation: "A secured credit card is backed by a fixed deposit. You deposit ₹10,000-₹50,000 and get a credit card with 80-90% of that amount as limit. Good for building CIBIL score.",
    difficulty: "medium",
    topic: "Credit Card Types",
    category: "Credit & Loans",
    indiaSpecific: true,
    relatedTerms: ["Secured Credit Card", "FD-backed Card", "CIBIL Building"],
    ageRelevance: "18-24",
    practicalExample: "Deposit ₹20,000 FD, get credit card with ₹18,000 limit to build credit history.",
    estimatedTime: 35
  },
  {
    levelNumber: 4,
    question: "What is the difference between debit and credit card?",
    options: ["No difference", "Debit uses your money, credit borrows money", "Debit is only for ATM", "Credit is free money"],
    correctAnswer: 1,
    explanation: "Debit card withdraws money directly from your bank account (your money). Credit card borrows money from bank that you must repay, usually with interest if not paid in full.",
    difficulty: "easy",
    topic: "Card Basics",
    category: "Banking",
    indiaSpecific: false,
    relatedTerms: ["Debit Card", "Credit Card", "Banking"],
    ageRelevance: "13-17",
    practicalExample: "Debit card: Spend ₹1,000 from your ₹10,000 balance. Credit card: Borrow ₹1,000, pay back later.",
    estimatedTime: 30
  },

  // Level 5: Indian Stock Market
  {
    levelNumber: 5,
    question: "What is NIFTY 50?",
    options: ["An insurance company", "Stock market index of top 50 companies on NSE", "A mutual fund", "A bank"],
    correctAnswer: 1,
    explanation: "NIFTY 50 is the flagship stock market index of National Stock Exchange (NSE) representing the weighted average of 50 largest Indian companies.",
    difficulty: "easy",
    topic: "Stock Indices",
    category: "Stock Market",
    indiaSpecific: true,
    relatedTerms: ["NIFTY", "NSE", "Stock Index", "NIFTY 50"],
    ageRelevance: "18-24",
    practicalExample: "When news says 'NIFTY is at 22,000', it means the average value of top 50 companies.",
    estimatedTime: 30
  },
  {
    levelNumber: 5,
    question: "What is a Demat account?",
    options: ["Dematerialized account to hold shares electronically", "A savings account", "A credit account", "A loan account"],
    correctAnswer: 0,
    explanation: "Demat (Dematerialized) account holds your stocks, bonds, and securities in electronic form. Mandatory for trading in Indian stock market.",
    difficulty: "easy",
    topic: "Trading Accounts",
    category: "Stock Market",
    indiaSpecific: true,
    relatedTerms: ["Demat Account", "Trading", "Shares", "NSDL", "CDSL"],
    ageRelevance: "18-24",
    practicalExample: "You need Demat account to buy shares of Reliance, TCS, or Infosys.",
    estimatedTime: 35
  },
  {
    levelNumber: 5,
    question: "Which is India's largest stock exchange by market capitalization?",
    options: ["BSE", "NSE", "MCX", "NYSE"],
    correctAnswer: 1,
    explanation: "NSE (National Stock Exchange) is India's largest stock exchange by market capitalization and trading volume, followed by BSE (Bombay Stock Exchange).",
    difficulty: "medium",
    topic: "Stock Exchanges",
    category: "Stock Market",
    indiaSpecific: true,
    relatedTerms: ["NSE", "BSE", "Stock Exchange"],
    ageRelevance: "18-24",
    practicalExample: "Most active trading happens on NSE with NIFTY 50 stocks.",
    estimatedTime: 30
  },
  {
    levelNumber: 5,
    question: "What is SEBI?",
    options: ["Securities and Exchange Board of India", "Stock Exchange Banking Institute", "Savings and Exchange Board", "Social Economic Bureau of India"],
    correctAnswer: 0,
    explanation: "SEBI (Securities and Exchange Board of India) is the regulatory body for securities market in India, protecting investor interests and regulating stock exchanges.",
    difficulty: "easy",
    topic: "Market Regulator",
    category: "Financial Regulations",
    indiaSpecific: true,
    relatedTerms: ["SEBI", "Stock Market Regulator", "Securities"],
    ageRelevance: "18-24",
    practicalExample: "SEBI ensures that companies and brokers follow rules to protect your investments.",
    estimatedTime: 30
  },
  {
    levelNumber: 5,
    question: "What are Zerodha and Groww?",
    options: ["Banks", "Discount stock brokers/investment platforms", "Insurance companies", "NBFCs"],
    correctAnswer: 1,
    explanation: "Zerodha and Groww are popular discount brokers in India where young investors can open Demat accounts and invest in stocks, mutual funds with low fees.",
    difficulty: "easy",
    topic: "Investment Platforms",
    category: "Stock Market",
    indiaSpecific: true,
    relatedTerms: ["Zerodha", "Groww", "Discount Broker", "Trading Platform"],
    ageRelevance: "18-24",
    practicalExample: "You can start investing in stocks with as little as ₹100 on Groww or Zerodha.",
    estimatedTime: 30
  },
  {
    levelNumber: 5,
    question: "What is SENSEX?",
    options: ["Sensitivity Index", "Stock Exchange Sensitive Index of BSE", "Sensible Exchange", "Sector Expert Index"],
    correctAnswer: 1,
    explanation: "SENSEX (Sensitive Index) is the benchmark stock market index of BSE representing 30 largest and most actively traded stocks on Bombay Stock Exchange.",
    difficulty: "easy",
    topic: "Stock Indices",
    category: "Stock Market",
    indiaSpecific: true,
    relatedTerms: ["SENSEX", "BSE", "Stock Index"],
    ageRelevance: "18-24",
    practicalExample: "SENSEX at 75,000 indicates the combined value of top 30 BSE companies.",
    estimatedTime: 30
  },
  {
    levelNumber: 5,
    question: "What is IPO?",
    options: ["International Payment Option", "Initial Public Offering", "Indian Profit Organization", "Investment Portfolio Option"],
    correctAnswer: 1,
    explanation: "IPO (Initial Public Offering) is when a private company offers shares to public for the first time. You can apply for IPO through your Demat account.",
    difficulty: "easy",
    topic: "IPO Basics",
    category: "Stock Market",
    indiaSpecific: false,
    relatedTerms: ["IPO", "Public Offering", "Shares"],
    ageRelevance: "18-24",
    practicalExample: "When Zomato went public in 2021, investors could buy shares through IPO.",
    estimatedTime: 35
  },
  {
    levelNumber: 5,
    question: "What is the minimum investment to buy shares in India?",
    options: ["₹100", "₹1,000", "₹10,000", "No minimum, just stock price"],
    correctAnswer: 3,
    explanation: "There's no minimum investment amount. You can buy even 1 share if you have enough money for that share's price plus brokerage charges.",
    difficulty: "medium",
    topic: "Investment Basics",
    category: "Stock Market",
    indiaSpecific: true,
    relatedTerms: ["Stock Investment", "Share Purchase"],
    ageRelevance: "18-24",
    practicalExample: "If TCS share is ₹3,500, you can buy 1 share for ₹3,500.",
    estimatedTime: 30
  },
  {
    levelNumber: 5,
    question: "What does 'bull market' mean?",
    options: ["Market selling bulls", "Market where prices are rising", "Market where prices are falling", "Market for animal trading"],
    correctAnswer: 1,
    explanation: "Bull market is when stock prices are rising or expected to rise. Opposite is bear market where prices fall. Bull represents upward movement (horns up).",
    difficulty: "easy",
    topic: "Market Terms",
    category: "Stock Market",
    indiaSpecific: false,
    relatedTerms: ["Bull Market", "Bear Market", "Market Trend"],
    ageRelevance: "18-24",
    practicalExample: "Indian market was in bull run when NIFTY went from 10,000 to 22,000.",
    estimatedTime: 30
  },
  {
    levelNumber: 5,
    question: "What is diversification in investing?",
    options: ["Buying only tech stocks", "Spreading investments across different assets", "Investing everything in one company", "Diverse hobbies"],
    correctAnswer: 1,
    explanation: "Diversification means spreading your investments across different companies, sectors, and asset types to reduce risk. Don't put all eggs in one basket!",
    difficulty: "medium",
    topic: "Investment Strategy",
    category: "Investments",
    indiaSpecific: false,
    relatedTerms: ["Diversification", "Risk Management", "Portfolio"],
    ageRelevance: "18-24",
    practicalExample: "Instead of investing ₹1 lakh in just Reliance, split it: ₹25K each in IT, Banking, Pharma, FMCG.",
    estimatedTime: 35
  },

  // Level 6: Insurance in India
  {
    levelNumber: 6,
    question: "What does LIC stand for?",
    options: ["Life Insurance Company", "Life Insurance Corporation of India", "Large Investment Company", "Low Interest Credit"],
    correctAnswer: 1,
    explanation: "LIC stands for Life Insurance Corporation of India. It's India's largest and government-owned life insurance company, providing various insurance policies.",
    difficulty: "easy",
    topic: "Insurance Companies",
    category: "Insurance",
    indiaSpecific: true,
    relatedTerms: ["LIC", "Life Insurance", "Insurance Corporation"],
    ageRelevance: "all",
    practicalExample: "LIC offers affordable life insurance policies like Jeevan Anand for Indian families.",
    estimatedTime: 25
  },
  {
    levelNumber: 6,
    question: "What is term insurance?",
    options: ["Insurance for a fixed term with only death benefit", "Insurance with investment", "Health insurance", "Car insurance"],
    correctAnswer: 0,
    explanation: "Term insurance provides life coverage for specific period (term). It only pays death benefit to nominees, has no investment component, making it cheapest form of life insurance.",
    difficulty: "easy",
    topic: "Life Insurance Types",
    category: "Insurance",
    indiaSpecific: false,
    relatedTerms: ["Term Insurance", "Life Insurance", "Death Benefit"],
    ageRelevance: "18-24",
    practicalExample: "₹1 crore term insurance for 30 years costs only ₹10,000-15,000 per year for young Indians.",
    estimatedTime: 35
  },
  {
    levelNumber: 6,
    question: "What is IRDAI?",
    options: ["Insurance Regulatory and Development Authority of India", "Indian Real Development Authority", "Insurance Rate Determination Authority", "Investment Regulation Department of India"],
    correctAnswer: 0,
    explanation: "IRDAI is Insurance Regulatory and Development Authority of India, which regulates and promotes insurance industry in India.",
    difficulty: "medium",
    topic: "Insurance Regulator",
    category: "Financial Regulations",
    indiaSpecific: true,
    relatedTerms: ["IRDAI", "Insurance Regulator"],
    ageRelevance: "18-24",
    practicalExample: "IRDAI ensures insurance companies settle claims fairly and operate ethically.",
    estimatedTime: 30
  },
  {
    levelNumber: 6,
    question: "What is health insurance?",
    options: ["Insurance for healthy people", "Insurance that covers medical expenses", "Insurance for gym", "Life insurance"],
    correctAnswer: 1,
    explanation: "Health insurance covers medical expenses like hospitalization, surgery, medicines. In India, having health insurance is crucial due to high medical costs.",
    difficulty: "easy",
    topic: "Health Insurance",
    category: "Insurance",
    indiaSpecific: false,
    relatedTerms: ["Health Insurance", "Medical Insurance", "Hospitalization"],
    ageRelevance: "all",
    practicalExample: "If hospitalized with ₹2 lakh bill, health insurance pays most of it based on your coverage.",
    estimatedTime: 30
  },
  {
    levelNumber: 6,
    question: "What is the minimum age to buy term insurance in India?",
    options: ["16 years", "18 years", "21 years", "25 years"],
    correctAnswer: 1,
    explanation: "Minimum age to buy term insurance in India is 18 years. Buying young gives lower premiums throughout policy term.",
    difficulty: "easy",
    topic: "Insurance Eligibility",
    category: "Insurance",
    indiaSpecific: true,
    relatedTerms: ["Term Insurance", "Age Requirement"],
    ageRelevance: "18-24",
    practicalExample: "Starting term insurance at 25 costs much less than starting at 35.",
    estimatedTime: 25
  },
  {
    levelNumber: 6,
    question: "What is sum assured in insurance?",
    options: ["Amount you pay as premium", "Amount insurance pays on claim", "Company's profit", "Agent's commission"],
    correctAnswer: 1,
    explanation: "Sum assured is the guaranteed amount insurance company pays to your nominee (in life insurance) or covers for medical expenses (in health insurance).",
    difficulty: "easy",
    topic: "Insurance Terms",
    category: "Insurance",
    indiaSpecific: false,
    relatedTerms: ["Sum Assured", "Coverage Amount", "Insurance Claim"],
    ageRelevance: "18-24",
    practicalExample: "If you have ₹50 lakh sum assured term insurance, nominee gets ₹50 lakh on your death.",
    estimatedTime: 30
  },
  {
    levelNumber: 6,
    question: "What is a nominee in insurance?",
    options: ["Person who sells insurance", "Person who gets insurance money after policyholder's death", "Insurance company", "Agent"],
    correctAnswer: 1,
    explanation: "Nominee is the person you designate to receive insurance benefits in case of your death. Usually spouse, parents, or children.",
    difficulty: "easy",
    topic: "Insurance Basics",
    category: "Insurance",
    indiaSpecific: false,
    relatedTerms: ["Nominee", "Beneficiary", "Insurance Claim"],
    ageRelevance: "18-24",
    practicalExample: "Your mother as nominee will get the insurance amount if something happens to you.",
    estimatedTime: 25
  },
  {
    levelNumber: 6,
    question: "What is cashless hospitalization?",
    options: ["Free hospital treatment", "Hospital accepts card payment", "Insurance company pays hospital directly", "EMI for treatment"],
    correctAnswer: 2,
    explanation: "Cashless hospitalization means insurance company settles hospital bills directly with network hospitals, so you don't pay from pocket and claim later.",
    difficulty: "medium",
    topic: "Health Insurance Features",
    category: "Insurance",
    indiaSpecific: false,
    relatedTerms: ["Cashless Treatment", "Network Hospital", "Health Insurance"],
    ageRelevance: "all",
    practicalExample: "In network hospitals, show health card and insurance handles payment directly.",
    estimatedTime: 35
  },
  {
    levelNumber: 6,
    question: "What is motor insurance in India?",
    options: ["Optional insurance", "Mandatory insurance for vehicles", "Insurance for motors only", "Insurance for mechanics"],
    correctAnswer: 1,
    explanation: "Motor insurance is mandatory by law in India for all vehicles. At minimum, you need third-party liability insurance to drive legally.",
    difficulty: "easy",
    topic: "Motor Insurance",
    category: "Insurance",
    indiaSpecific: true,
    relatedTerms: ["Motor Insurance", "Vehicle Insurance", "Third-party Insurance"],
    ageRelevance: "18-24",
    practicalExample: "You must have valid insurance to drive your bike or car in India, else police can fine you.",
    estimatedTime: 30
  },
  {
    levelNumber: 6,
    question: "What is the ideal health insurance coverage for young Indians?",
    options: ["₹50,000", "₹1-2 lakhs", "₹5-10 lakhs", "₹50 lakhs"],
    correctAnswer: 2,
    explanation: "Financial experts recommend ₹5-10 lakhs health insurance for young Indians, considering rising medical costs. Family coverage should be higher (₹15-25 lakhs).",
    difficulty: "medium",
    topic: "Insurance Planning",
    category: "Insurance",
    indiaSpecific: true,
    relatedTerms: ["Health Insurance", "Coverage Amount"],
    ageRelevance: "18-24",
    practicalExample: "ICU costs ₹10,000-50,000 per day in cities, making ₹5-10 lakh coverage necessary.",
    estimatedTime: 35
  },

  // Level 7: Indian Taxation
  {
    levelNumber: 7,
    question: "What does GST stand for?",
    options: ["General Sales Tax", "Goods and Services Tax", "Government Standard Tax", "Global Service Tax"],
    correctAnswer: 1,
    explanation: "GST stands for Goods and Services Tax. It's an indirect tax implemented in India in 2017 that replaced multiple taxes like VAT, service tax, etc.",
    difficulty: "easy",
    topic: "GST Basics",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["GST", "Indirect Tax", "Tax Reform"],
    ageRelevance: "18-24",
    practicalExample: "When you pay ₹118 for ₹100 product, ₹18 is 18% GST.",
    estimatedTime: 30
  },
  {
    levelNumber: 7,
    question: "What are the GST tax slabs in India?",
    options: ["0%, 5%, 12%, 18%, 28%", "10%, 20%, 30%", "5%, 10%, 15%", "Only 18%"],
    correctAnswer: 0,
    explanation: "GST has five tax slabs: 0% (essential items), 5%, 12%, 18% (most goods/services), and 28% (luxury items). Some items have cess on top.",
    difficulty: "medium",
    topic: "GST Rates",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["GST Slabs", "Tax Rates", "GST"],
    ageRelevance: "18-24",
    practicalExample: "Rice (0% GST), Hotel room (12% GST), Phone (18% GST), Luxury car (28% GST).",
    estimatedTime: 35
  },
  {
    levelNumber: 7,
    question: "What is Section 80C in Income Tax?",
    options: ["Crime section", "Tax deduction up to ₹1.5 lakhs for investments", "Tax on companies", "Property tax"],
    correctAnswer: 1,
    explanation: "Section 80C allows tax deduction up to ₹1.5 lakh per year for investments in PPF, ELSS, LIC, tuition fees, home loan principal, NSC, etc.",
    difficulty: "medium",
    topic: "Tax Deductions",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["Section 80C", "Tax Deduction", "Tax Saving"],
    ageRelevance: "18-24",
    practicalExample: "Invest ₹1.5 lakh in PPF and save ₹46,800 tax (in 30% tax bracket).",
    estimatedTime: 35
  },
  {
    levelNumber: 7,
    question: "What is the income tax exemption limit for individuals in India (basic)?",
    options: ["₹1 lakh", "₹2.5 lakhs (old regime)", "₹5 lakhs", "₹10 lakhs"],
    correctAnswer: 1,
    explanation: "Under old tax regime, income up to ₹2.5 lakhs is tax-free for individuals. Under new regime, exemption is ₹3 lakhs. Rebate under 87A can make up to ₹7 lakhs tax-free in new regime.",
    difficulty: "medium",
    topic: "Tax Exemptions",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["Tax Exemption", "Income Tax", "Tax-free Income"],
    ageRelevance: "18-24",
    practicalExample: "If you earn ₹2 lakh per year, you pay zero income tax.",
    estimatedTime: 35
  },
  {
    levelNumber: 7,
    question: "What is ITR?",
    options: ["International Tax Return", "Income Tax Return", "Investment Tax Record", "Indian Tax Rate"],
    correctAnswer: 1,
    explanation: "ITR (Income Tax Return) is a form to declare your income, deductions, and taxes paid to Income Tax Department. Filing ITR is mandatory if income exceeds basic exemption limit.",
    difficulty: "easy",
    topic: "Tax Filing",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["ITR", "Income Tax Return", "Tax Filing"],
    ageRelevance: "18-24",
    practicalExample: "File ITR online on income tax portal by July 31 every year.",
    estimatedTime: 30
  },
  {
    levelNumber: 7,
    question: "What is TDS?",
    options: ["Tax Deducted at Source", "Total Deducted Salary", "Tax Determination System", "Time Deposit Scheme"],
    correctAnswer: 0,
    explanation: "TDS (Tax Deducted at Source) means tax is deducted before paying you. Employers deduct TDS from salary, banks deduct from interest, etc., and deposit to government.",
    difficulty: "easy",
    topic: "TDS Basics",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["TDS", "Tax Deduction", "Source Tax"],
    ageRelevance: "18-24",
    practicalExample: "If salary is ₹50,000, company deducts ₹5,000 TDS and pays you ₹45,000.",
    estimatedTime: 30
  },
  {
    levelNumber: 7,
    question: "What is Form 16?",
    options: ["Driving license form", "TDS certificate from employer", "PAN application form", "Bank account form"],
    correctAnswer: 1,
    explanation: "Form 16 is TDS certificate issued by employer showing your salary, deductions, and tax deducted. Needed for filing ITR.",
    difficulty: "easy",
    topic: "Tax Documents",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["Form 16", "TDS Certificate", "Salary Certificate"],
    ageRelevance: "18-24",
    practicalExample: "Download Form 16 from employer's portal to file your income tax return.",
    estimatedTime: 30
  },
  {
    levelNumber: 7,
    question: "What is the due date for filing ITR for salaried individuals?",
    options: ["March 31", "July 31", "December 31", "No deadline"],
    correctAnswer: 1,
    explanation: "For salaried individuals and those not requiring audit, ITR filing deadline is July 31 of the assessment year (for previous financial year income).",
    difficulty: "medium",
    topic: "Tax Deadlines",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["ITR Deadline", "Tax Filing", "Due Date"],
    ageRelevance: "18-24",
    practicalExample: "File FY 2023-24 income tax return by July 31, 2024.",
    estimatedTime: 30
  },
  {
    levelNumber: 7,
    question: "What is ELSS?",
    options: ["Extra Long Saving Scheme", "Equity Linked Savings Scheme", "Electronic Loan Service System", "Emergency Life Support System"],
    correctAnswer: 1,
    explanation: "ELSS (Equity Linked Savings Scheme) is a type of mutual fund that invests in stocks and qualifies for Section 80C tax deduction. Lock-in period is 3 years.",
    difficulty: "medium",
    topic: "Tax-saving Investments",
    category: "Investments",
    indiaSpecific: true,
    relatedTerms: ["ELSS", "Tax Saving", "Mutual Fund"],
    ageRelevance: "18-24",
    practicalExample: "Invest ₹1.5 lakh in ELSS, save tax and potentially earn 12-15% returns.",
    estimatedTime: 35
  },
  {
    levelNumber: 7,
    question: "What is HRA?",
    options: ["House Rent Allowance (tax exempt component)", "Home Rental Agency", "High Rate Account", "Housing Research Authority"],
    correctAnswer: 0,
    explanation: "HRA (House Rent Allowance) is part of salary given for rent. You can claim HRA exemption in income tax if you live in rented house and submit rent receipts.",
    difficulty: "easy",
    topic: "Salary Components",
    category: "Taxation",
    indiaSpecific: true,
    relatedTerms: ["HRA", "House Rent Allowance", "Tax Exemption"],
    ageRelevance: "18-24",
    practicalExample: "If your rent is ₹10,000/month, you can claim HRA exemption and reduce taxable income.",
    estimatedTime: 30
  }
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await Level.deleteMany({});
    await Question.deleteMany({});
    console.log('Cleared existing data');

    // Insert levels
    await Level.insertMany(levels);
    console.log('Levels inserted successfully');

    // Insert questions
    await Question.insertMany(questions);
    console.log('Questions inserted successfully');

    console.log('Database seeded successfully with India-specific content!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
